-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 13:25:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
----------------------------------------------------
-- Schema apeboxe2
-- -----------------------------------------------------
CREATE DATABASE  IF NOT EXISTS `apeboxe2` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `apeboxe2`;

-- -----------------------------------------------------
-- Table `apeboxe2`.`tb_boleto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_boleto` ;

CREATE TABLE IF NOT EXISTS `tb_boleto` (
  `id_boleto` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `referencia` VARCHAR(80) NOT NULL,
  `data_vencimento` VARCHAR(45) NOT NULL,
  `link` VARCHAR(300) NOT NULL,
  `linkdownload` VARCHAR(300) NOT NULL,
  `linhadigitavel` VARCHAR(200) NOT NULL,
  `barcodeNumber` VARCHAR(45) NOT NULL,
  `status_boleto` INT(5) NOT NULL,
  PRIMARY KEY (`id_boleto`)
  ) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `apeboxe2`.`tb_atleta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_atleta` ;

CREATE TABLE IF NOT EXISTS `tb_atleta` (
  `id_alteta` INT(5) ZEROFILL NOT NULL,
  `nome_atleta` VARCHAR(150) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `datanascimento` VARCHAR(20) NOT NULL,
  `sexo` VARCHAR(20) NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(20) NOT NULL,
  `rua` VARCHAR(80) NOT NULL,
  `complemento` VARCHAR(100) NOT NULL,
  `num` INT(10) NOT NULL,
  `bairro` VARCHAR(80) NOT NULL,
  `cidade` VARCHAR(80) NOT NULL,
  `uf` VARCHAR(45) NOT NULL,
  `academia` VARCHAR(150) NOT NULL,
  `professor` VARCHAR(150) NOT NULL,
  `status_inscricao` INT(5) NOT NULL,
  `data_registro` DATETIME NULL,
  `id_boleto` INT,
  PRIMARY KEY (`id_alteta`),
  KEY `FK_atleta_boleto_idx` (`id_boleto`),
  CONSTRAINT `fk_atleta_boleto` FOREIGN KEY (`id_boleto`) REFERENCES `tb_boleto` (`id_boleto`) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE=InnoDB DEFAULT CHARSET=utf8;




-- -----------------------------------------------------
-- Table `apeboxe2`.`tb_tecnico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_tecnico`;

CREATE TABLE IF NOT EXISTS `tb_tecnico`(
  `id_tecnico` INT(5) ZEROFILL NOT NULL,
  `nome_tecnico` VARCHAR(150) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `datanascimento` VARCHAR(20) NOT NULL,
  `sexo` VARCHAR(20) NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(20) NOT NULL,
  `rua` VARCHAR(80) NOT NULL,
  `complemento` VARCHAR(100) NOT NULL,
  `num` INT(10) NOT NULL,
  `bairro` VARCHAR(80) NOT NULL,
  `cidade` VARCHAR(80) NOT NULL,
  `uf` VARCHAR(45) NOT NULL,
  `academia` VARCHAR(150) NOT NULL,
  `status_inscricao` INT(5) NOT NULL,
  `data_registro` DATETIME NOT NULL,
  `id_boleto` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`id_tecnico`),
  KEY `FK_tecnico_boleto_idx` (`id_boleto`),
  CONSTRAINT `fk_tecnico_boleto` FOREIGN KEY (`id_boleto`) REFERENCES `tb_boleto` (`id_boleto`) ON DELETE NO ACTION ON UPDATE NO ACTION
  
  )ENGINE=InnoDB DEFAULT CHARSET=utf8;




-- -----------------------------------------------------
-- Table `apeboxe2`.`tb_academia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apeboxe2`.`tb_academia` ;

CREATE TABLE IF NOT EXISTS `apeboxe2`.`tb_academia` (
  `id_academia` INT(5) ZEROFILL NOT NULL,
  `nome_academia` VARCHAR(150) NOT NULL,
  `nome_responsavel` VARCHAR(150) NULL,
  `tb_academiacol` VARCHAR(45) NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `datafundacao` VARCHAR(20) NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(20) NOT NULL,
  `rua` VARCHAR(80) NOT NULL,
  `complemento` VARCHAR(100) NOT NULL,
  `num` INT(10) NOT NULL,
  `bairro` VARCHAR(80) NOT NULL,
  `cidade` VARCHAR(80) NOT NULL,
  `uf` VARCHAR(45) NOT NULL,
  `status_inscricao` INT(5) NOT NULL,
  `data_registro` DATETIME NOT NULL,
  `id_boleto` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`id_academia`),
  KEY `FK_academia_boleto_idx` (`id_boleto`),
  CONSTRAINT `fk_academia_boleto` FOREIGN KEY (`id_boleto`) REFERENCES `tb_boleto` (`id_boleto`) ON DELETE NO ACTION ON UPDATE NO ACTION
  )ENGINE=InnoDB DEFAULT CHARSET=utf8;

